### ISSUE TITLE
Bias weights in convolution layers

### ISSUE THREAD

**Issue by xpngzhng** [fizyr/keras-models#1]
Hi,
I use h5py to parse the ResNet50 model and do not find the bias weights in convolution layers.
If my discovery is correct, why discard the bias weights?

**Comment by hgaiser** [comment]
keras-resnet follows the original Caffe implementation (these weights are also purely ported versions of the Caffe weights). The original implementation disabled many biases: https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt#L70

**Comment by xpngzhng** [comment]
@hgaiser thank you for pointing out the prototxt, all convolution layers do not have biases except the conv1 layer.
And I also check the ResNet50 model in https://github.com/fchollet/deep-learning-models/releases, all convolution layers have biases, but the biases are all zero except that in conv1 layer. That ResNet50 model and the one in this repo should be the same.

I sitll have a question, is the code for converting the ResNet caffe models to the keras models in this repo publicly available?
As far as I know, maybe the code https://github.com/MarcBS/keras/blob/master/keras/caffe/caffe2keras.py can do the conversion.

**Comment by hgaiser** [comment]
The code is available, but very specific to ResNet: https://github.com/broadinstitute/keras-resnet/tree/master/tools
